name: Release Commit to pkg.pr.new

on:
  pull_request: {}

jobs:
  release-commit:
    if: github.repository_owner != "so1ve-starters"
    uses: so1ve/workflows/.github/workflows/release-commit.yml@v1
